# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

# [[social]]
#     identifier = "social"
#     name       = "Social"
#     url        = "https://social.com"

#     [social.params]
#         icon = "brand-SOCIAL"

[[social]]
    identifier = "instagram"
    name       = "Instagram"
    url        = "https://instagram.com/paustagrams"

    [social.params]
        icon = "brand-instagram"

[[social]]
    identifier = "linkedin"
    name       = "LinkedIn"
    url        = "https://linkedin.com/in/p-geronimo"

    [social.params]
        icon = "brand-linkedin"


